version: '3.8'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./dist/frontend:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
    networks:
      - shared-network

networks:
  shared-network:
    external: true
